Deterministic js
davehunt/raptor-studio pull request #6
Opened 2019-02-08 15:36 UTC by bebef1987

2019-02-08 15:42 UTC, davehunt requested changes

2019-02-08 15:42 UTC, davehunt commented on Pipfile
> +python_version = "3.6"
We should do this in a separate patch/pull request.

2019-02-08 15:42 UTC, davehunt commented on studio.py
> +@click.option("--deterministic", required=True, help="Use deterministic JS in the recording")
Is there a reason not to run with determinism? We can be opinionated here, so I think we should just make this the default and not provide an option to disable it.

2019-02-08 15:42 UTC, davehunt commented on studio.py
> +        input("What is your name? ")
Is this debug?

2019-02-10 21:11 UTC, bebef1987 commented
@davehunt as we have massive changes closing this branch

2019-02-10 21:11 UTC, closed without merging